python 3 conversion
adsabs/harbour-service pull request #36
Opened 2021-02-22 19:02 UTC by golnazads

2021-02-24 17:12 UTC, kelockhart requested changes
Nearly there! The only main comment is that we'd decided (somewhere in Slack) that we don't need to keep this code backwards compatible with Python 2, so you can remove those lines.

2021-02-24 17:12 UTC, kelockhart commented on dev-requirements.txt
> +httpretty==0.8.10; python_version < '3.0'
I _think_ we decided to not make the code backwards compatible with Python 2, so you can remove these.

2021-02-24 17:12 UTC, kelockhart commented on harbour/app.py
> +standard_library.install_aliases()
These two lines are only needed for Python 2 backwards-compatible code, so you can remove them.

2021-02-24 17:12 UTC, kelockhart commented on harbour/client.py
> +from builtins import object
Also only needed for Python 2-compatible code.

2021-02-24 17:12 UTC, kelockhart commented on harbour/utils.py
> +            if expected_key not in list(post_data.keys()):
The syntax `if key in dict.keys()` works ok here in Python 3, without the `list()` - the converter script is really conservative about adding `list()` everywhere, even when it's not needed.

2021-02-24 17:12 UTC, kelockhart commented on harbour/views.py
> +standard_library.install_aliases()
These two lines can be removed.

2021-03-02 21:24 UTC, golnazads commented on config.py
> +SQLALCHEMY_TRACK_MODIFICATIONS = True
somehow I did not get notifications of these comments!
OK, shall change to False.

2021-03-02 21:25 UTC, golnazads commented on dev-requirements.txt
> +httpretty==0.8.10; python_version < '3.0'
OK.

2021-03-02 21:27 UTC, golnazads commented on harbour/app.py
> +standard_library.install_aliases()
I think these were added automatically when I run futurize. So you are saying I have to go and remove it from all other ones too, lol.

2021-03-02 21:29 UTC, golnazads commented on harbour/utils.py
> +            if expected_key not in list(post_data.keys()):
I think this is also part of the futurize! OK, thank you.

2021-03-02 21:30 UTC, golnazads commented on harbour/views.py
> +standard_library.install_aliases()
done.

2021-03-03 14:50 UTC, kelockhart approved these changes
Looks good!

2021-03-29 20:40 UTC, merged